loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  config:
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

promtail:
  enabled: true
  config:
    snippets:
      extraScrapeConfigs: |
        - job_name: pacman-logs
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_pod_label_app]
              regex: pacman-.*
              action: keep

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 5Gi
  # Create only one datasource file with clear default settings
  datasources:
    datasources.yaml:
      apiVersion: 1
      deleteDatasources:
        - name: Loki
          orgId: 1
        - name: Prometheus
          orgId: 1
        - name: Alertmanager
          orgId: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
          isDefault: false
  # Disable other potential datasource configurations
  sidecar:
    datasources:
      enabled: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards