version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - pacman-net

  backend:
    build:
      context: .
      dockerfile: multiplayer/Dockerfile
    ports:
      - "5050:5050"
    networks:
      - pacman-net
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: pacman-js/Dockerfile
    ports:
      - "1234:1234"
    networks:
      - pacman-net
    depends_on:
      - backend

networks:
  pacman-net:
