version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: multiplayer/Dockerfile
    ports:
      - "5050:5050"
    networks:
      - pacman-net

  frontend:
    build:
      context: .
      dockerfile: pacman-js/Dockerfile
    ports:
      - "1234:1234"
    networks:
      - pacman-net
    depends_on:
      - backend

networks:
  pacman-net:
